---
version: "2.0"

services:
  finetune:
    image: tmontfort/finetune:latest
    expose:
      - port: 8000
        as: 80
        to:
          - global: true

profiles:
  compute:
    finetune:
      resources:
        cpu:
          units: 8
        memory:
          size: 50Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
        storage:
          - size: 40Gi
  placement:
    akash:
      pricing:
        falcon7b: 
          denom: uakt
          amount: 100000

deployment:
  finetune:
    akash:
      profile: finetune
      count: 1
